In [2]:
import pandas

In [3]:
df = pandas.read_csv("ARROW.csv")

In [4]:
df

     frequency  Radial Velocity  Intensity  Unnamed: 3  Unnamed: 4
0      -800000           168.97      2.412         NaN         NaN
1      -795000           167.91      2.378         NaN         NaN
2      -790000           166.85      2.344         NaN         NaN
3      -785000           165.80      2.344         NaN         NaN
4      -780000           164.74      2.324         NaN         NaN
5      -775000           163.69      2.327         NaN         NaN
6      -770000           162.63      2.341         NaN         NaN
7      -765000           161.57      2.334         NaN         NaN
8      -760000           160.52      2.354         NaN         NaN
9      -755000           159.46      2.393         NaN         NaN
10     -750000           158.41      2.383         NaN         NaN
11     -745000           157.35      2.363         NaN         NaN
12     -740000           156.29      2.358         NaN         NaN
13     -735000           155.24      2.363         NaN         NaN
14     -730000           154.18      2.363         NaN         NaN
15     -725000           153.13      2.341         NaN         NaN
16     -720000           152.07      2.363         NaN         NaN
17     -715000           151.01      2.363         NaN         NaN
18     -710000           149.96      2.363         NaN         NaN
19     -705000           148.90      2.351         NaN         NaN
20     -700000           147.85      2.344         NaN         NaN
21     -695000           146.79      2.344         NaN         NaN
22     -690000           145.73      2.341         NaN         NaN
23     -685000           144.68      2.361         NaN         NaN
24     -680000           143.62      2.385         NaN         NaN
25     -675000           142.57      2.397         NaN         NaN
26     -670000           141.51      2.380         NaN         NaN
27     -665000           140.45      2.373         NaN         NaN
28     -660000           139.40      2.383         NaN         NaN
29     -655000           138.34      2.371         NaN         NaN
..         ...              ...        ...         ...         ...
371    1055000          -222.82      2.988         NaN         NaN
372    1060000          -223.88      2.998         NaN         NaN
373    1065000          -224.94      3.008         NaN         NaN
374    1070000          -225.99      3.049         NaN         NaN
375    1075000          -227.05      3.018         NaN         NaN
376    1080000          -228.10      2.998         NaN         NaN
377    1085000          -229.16      2.996         NaN         NaN
378    1090000          -230.22      3.044         NaN         NaN
379    1095000          -231.27      3.035         NaN         NaN
380    1100000          -232.33      3.047         NaN         NaN
381    1105000          -233.38      3.022         NaN         NaN
382    1110000          -234.44      3.022         NaN         NaN
383    1115000          -235.50      3.047         NaN         NaN
384    1120000          -236.55      3.047         NaN         NaN
385    1125000          -237.61      3.108         NaN         NaN
386    1130000          -238.67      3.135         NaN         NaN
387    1135000          -239.72      3.125         NaN         NaN
388    1140000          -240.78      3.125         NaN         NaN
389    1145000          -241.83      3.132         NaN         NaN
390    1150000          -242.89      3.096         NaN         NaN
391    1155000          -243.95      3.066         NaN         NaN
392    1160000          -245.00      3.098         NaN         NaN
393    1165000          -246.06      3.086         NaN         NaN
394    1170000          -247.11      3.103         NaN         NaN
395    1175000          -248.17      3.083         NaN         NaN
396    1180000          -249.23      3.074         NaN         NaN
397    1185000          -250.28      3.083         NaN         NaN
398    1190000          -251.34      3.076         NaN         NaN
399    1195000          -252.39      3.083         NaN         NaN
400    1200000          -253.45      3.054         NaN         NaN

[401 rows x 5 columns]